<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            ['id' => 'abw', 'internal_name' => 'Aruba', 'backward_compatibility' => 'aw'],
            ['id' => 'afg', 'internal_name' => 'Afghanistan', 'backward_compatibility' => 'af'],
            ['id' => 'ago', 'internal_name' => 'Angola', 'backward_compatibility' => 'ao'],
            ['id' => 'aia', 'internal_name' => 'Anguilla', 'backward_compatibility' => 'ai'],
            ['id' => 'ala', 'internal_name' => 'Åland Islands', 'backward_compatibility' => 'ax'],
            ['id' => 'alb', 'internal_name' => 'Albania', 'backward_compatibility' => 'al'],
            ['id' => 'and', 'internal_name' => 'Andorra', 'backward_compatibility' => 'ad'],
            ['id' => 'are', 'internal_name' => 'United Arab Emirates', 'backward_compatibility' => 'ae'],
            ['id' => 'arg', 'internal_name' => 'Argentina', 'backward_compatibility' => 'ar'],
            ['id' => 'arm', 'internal_name' => 'Armenia', 'backward_compatibility' => 'am'],
            ['id' => 'asm', 'internal_name' => 'American Samoa', 'backward_compatibility' => 'as'],
            ['id' => 'ata', 'internal_name' => 'Antarctica', 'backward_compatibility' => 'aq'],
            ['id' => 'atf', 'internal_name' => 'French Southern Territories', 'backward_compatibility' => 'tf'],
            ['id' => 'atg', 'internal_name' => 'Antigua and Barbuda', 'backward_compatibility' => 'ag'],
            ['id' => 'aus', 'internal_name' => 'Australia', 'backward_compatibility' => 'au'],
            ['id' => 'aut', 'internal_name' => 'Austria', 'backward_compatibility' => 'at'],
            ['id' => 'aze', 'internal_name' => 'Azerbaijan', 'backward_compatibility' => 'az'],
            ['id' => 'bdi', 'internal_name' => 'Burundi', 'backward_compatibility' => 'bi'],
            ['id' => 'bel', 'internal_name' => 'Belgium', 'backward_compatibility' => 'be'],
            ['id' => 'ben', 'internal_name' => 'Benin', 'backward_compatibility' => 'bj'],
            ['id' => 'bes', 'internal_name' => 'Bonaire, Sint Eustatius and Saba', 'backward_compatibility' => 'bq'],
            ['id' => 'bfa', 'internal_name' => 'Burkina Faso', 'backward_compatibility' => 'bf'],
            ['id' => 'bgd', 'internal_name' => 'Bangladesh', 'backward_compatibility' => 'bd'],
            ['id' => 'bgr', 'internal_name' => 'Bulgaria', 'backward_compatibility' => 'bg'],
            ['id' => 'bhr', 'internal_name' => 'Bahrain', 'backward_compatibility' => 'bh'],
            ['id' => 'bhs', 'internal_name' => 'Bahamas', 'backward_compatibility' => 'bs'],
            ['id' => 'bih', 'internal_name' => 'Bosnia and Herzegovina', 'backward_compatibility' => 'ba'],
            ['id' => 'blm', 'internal_name' => 'Saint Barthélemy', 'backward_compatibility' => 'bl'],
            ['id' => 'blr', 'internal_name' => 'Belarus', 'backward_compatibility' => 'by'],
            ['id' => 'blz', 'internal_name' => 'Belize', 'backward_compatibility' => 'bz'],
            ['id' => 'bmu', 'internal_name' => 'Bermuda', 'backward_compatibility' => 'bm'],
            ['id' => 'bol', 'internal_name' => 'Bolivia, Plurinational State of', 'backward_compatibility' => 'bo'],
            ['id' => 'bra', 'internal_name' => 'Brazil', 'backward_compatibility' => 'br'],
            ['id' => 'brb', 'internal_name' => 'Barbados', 'backward_compatibility' => 'bb'],
            ['id' => 'brn', 'internal_name' => 'Brunei Darussalam', 'backward_compatibility' => 'bn'],
            ['id' => 'btn', 'internal_name' => 'Bhutan', 'backward_compatibility' => 'bt'],
            ['id' => 'bvt', 'internal_name' => 'Bouvet Island', 'backward_compatibility' => 'bv'],
            ['id' => 'bwa', 'internal_name' => 'Botswana', 'backward_compatibility' => 'bw'],
            ['id' => 'caf', 'internal_name' => 'Central African Republic', 'backward_compatibility' => 'cf'],
            ['id' => 'can', 'internal_name' => 'Canada', 'backward_compatibility' => 'ca'],
            ['id' => 'cck', 'internal_name' => 'Cocos (Keeling) Islands', 'backward_compatibility' => 'cc'],
            ['id' => 'che', 'internal_name' => 'Switzerland', 'backward_compatibility' => 'ch'],
            ['id' => 'chl', 'internal_name' => 'Chile', 'backward_compatibility' => 'cl'],
            ['id' => 'chn', 'internal_name' => 'China', 'backward_compatibility' => 'cn'],
            ['id' => 'civ', 'internal_name' => 'Côte d\'Ivoire', 'backward_compatibility' => 'ci'],
            ['id' => 'cmr', 'internal_name' => 'Cameroon', 'backward_compatibility' => 'cm'],
            ['id' => 'cod', 'internal_name' => 'Congo, Democratic Republic of the', 'backward_compatibility' => 'cd'],
            ['id' => 'cog', 'internal_name' => 'Congo', 'backward_compatibility' => 'cg'],
            ['id' => 'cok', 'internal_name' => 'Cook Islands', 'backward_compatibility' => 'ck'],
            ['id' => 'col', 'internal_name' => 'Colombia', 'backward_compatibility' => 'co'],
            ['id' => 'com', 'internal_name' => 'Comoros', 'backward_compatibility' => 'km'],
            ['id' => 'cpv', 'internal_name' => 'Cabo Verde', 'backward_compatibility' => 'cv'],
            ['id' => 'cri', 'internal_name' => 'Costa Rica', 'backward_compatibility' => 'cr'],
            ['id' => 'cub', 'internal_name' => 'Cuba', 'backward_compatibility' => 'cu'],
            ['id' => 'cuw', 'internal_name' => 'Curaçao', 'backward_compatibility' => 'cw'],
            ['id' => 'cxr', 'internal_name' => 'Christmas Island', 'backward_compatibility' => 'cx'],
            ['id' => 'cym', 'internal_name' => 'Cayman Islands', 'backward_compatibility' => 'ky'],
            ['id' => 'cyp', 'internal_name' => 'Cyprus', 'backward_compatibility' => 'cy'],
            ['id' => 'cze', 'internal_name' => 'Czechia', 'backward_compatibility' => 'cz'],
            ['id' => 'deu', 'internal_name' => 'Germany', 'backward_compatibility' => 'de'],
            ['id' => 'dji', 'internal_name' => 'Djibouti', 'backward_compatibility' => 'dj'],
            ['id' => 'dma', 'internal_name' => 'Dominica', 'backward_compatibility' => 'dm'],
            ['id' => 'dnk', 'internal_name' => 'Denmark', 'backward_compatibility' => 'dk'],
            ['id' => 'dom', 'internal_name' => 'Dominican Republic', 'backward_compatibility' => 'do'],
            ['id' => 'dza', 'internal_name' => 'Algeria', 'backward_compatibility' => 'dz'],
            ['id' => 'ecu', 'internal_name' => 'Ecuador', 'backward_compatibility' => 'ec'],
            ['id' => 'egy', 'internal_name' => 'Egypt', 'backward_compatibility' => 'eg'],
            ['id' => 'eri', 'internal_name' => 'Eritrea', 'backward_compatibility' => 'er'],
            ['id' => 'esh', 'internal_name' => 'Western Sahara', 'backward_compatibility' => 'eh'],
            ['id' => 'esp', 'internal_name' => 'Spain', 'backward_compatibility' => 'es'],
            ['id' => 'est', 'internal_name' => 'Estonia', 'backward_compatibility' => 'ee'],
            ['id' => 'eth', 'internal_name' => 'Ethiopia', 'backward_compatibility' => 'et'],
            ['id' => 'fin', 'internal_name' => 'Finland', 'backward_compatibility' => 'fi'],
            ['id' => 'fji', 'internal_name' => 'Fiji', 'backward_compatibility' => 'fj'],
            ['id' => 'flk', 'internal_name' => 'Falkland Islands (Malvinas)', 'backward_compatibility' => 'fk'],
            ['id' => 'fra', 'internal_name' => 'France', 'backward_compatibility' => 'fr'],
            ['id' => 'fro', 'internal_name' => 'Faroe Islands', 'backward_compatibility' => 'fo'],
            ['id' => 'fsm', 'internal_name' => 'Micronesia, Federated States of', 'backward_compatibility' => 'fm'],
            ['id' => 'gab', 'internal_name' => 'Gabon', 'backward_compatibility' => 'ga'],
            ['id' => 'gbr', 'internal_name' => 'United Kingdom of Great Britain and Northern Ireland', 'backward_compatibility' => 'gb'],
            ['id' => 'geo', 'internal_name' => 'Georgia', 'backward_compatibility' => 'ge'],
            ['id' => 'ggy', 'internal_name' => 'Guernsey', 'backward_compatibility' => 'gg'],
            ['id' => 'gha', 'internal_name' => 'Ghana', 'backward_compatibility' => 'gh'],
            ['id' => 'gib', 'internal_name' => 'Gibraltar', 'backward_compatibility' => 'gi'],
            ['id' => 'gin', 'internal_name' => 'Guinea', 'backward_compatibility' => 'gn'],
            ['id' => 'glp', 'internal_name' => 'Guadeloupe', 'backward_compatibility' => 'gp'],
            ['id' => 'gmb', 'internal_name' => 'Gambia', 'backward_compatibility' => 'gm'],
            ['id' => 'gnb', 'internal_name' => 'Guinea-Bissau', 'backward_compatibility' => 'gw'],
            ['id' => 'gnq', 'internal_name' => 'Equatorial Guinea', 'backward_compatibility' => 'gq'],
            ['id' => 'grc', 'internal_name' => 'Greece', 'backward_compatibility' => 'gr'],
            ['id' => 'grd', 'internal_name' => 'Grenada', 'backward_compatibility' => 'gd'],
            ['id' => 'grl', 'internal_name' => 'Greenland', 'backward_compatibility' => 'gl'],
            ['id' => 'gtm', 'internal_name' => 'Guatemala', 'backward_compatibility' => 'gt'],
            ['id' => 'guf', 'internal_name' => 'French Guiana', 'backward_compatibility' => 'gf'],
            ['id' => 'gum', 'internal_name' => 'Guam', 'backward_compatibility' => 'gu'],
            ['id' => 'guy', 'internal_name' => 'Guyana', 'backward_compatibility' => 'gy'],
            ['id' => 'hkg', 'internal_name' => 'Hong Kong', 'backward_compatibility' => 'hk'],
            ['id' => 'hmd', 'internal_name' => 'Heard Island and McDonald Islands', 'backward_compatibility' => 'hm'],
            ['id' => 'hnd', 'internal_name' => 'Honduras', 'backward_compatibility' => 'hn'],
            ['id' => 'hrv', 'internal_name' => 'Croatia', 'backward_compatibility' => 'hr'],
            ['id' => 'hti', 'internal_name' => 'Haiti', 'backward_compatibility' => 'ht'],
            ['id' => 'hun', 'internal_name' => 'Hungary', 'backward_compatibility' => 'hu'],
            ['id' => 'idn', 'internal_name' => 'Indonesia', 'backward_compatibility' => 'id'],
            ['id' => 'imn', 'internal_name' => 'Isle of Man', 'backward_compatibility' => 'im'],
            ['id' => 'ind', 'internal_name' => 'India', 'backward_compatibility' => 'in'],
            ['id' => 'iot', 'internal_name' => 'British Indian Ocean Territory', 'backward_compatibility' => 'io'],
            ['id' => 'irl', 'internal_name' => 'Ireland', 'backward_compatibility' => 'ie'],
            ['id' => 'irn', 'internal_name' => 'Iran, Islamic Republic of', 'backward_compatibility' => 'ir'],
            ['id' => 'irq', 'internal_name' => 'Iraq', 'backward_compatibility' => 'iq'],
            ['id' => 'isl', 'internal_name' => 'Iceland', 'backward_compatibility' => 'is'],
            ['id' => 'isr', 'internal_name' => 'Israel', 'backward_compatibility' => 'il'],
            ['id' => 'ita', 'internal_name' => 'Italy', 'backward_compatibility' => 'it'],
            ['id' => 'jam', 'internal_name' => 'Jamaica', 'backward_compatibility' => 'jm'],
            ['id' => 'jey', 'internal_name' => 'Jersey', 'backward_compatibility' => 'je'],
            ['id' => 'jor', 'internal_name' => 'Jordan', 'backward_compatibility' => 'jo'],
            ['id' => 'jpn', 'internal_name' => 'Japan', 'backward_compatibility' => 'jp'],
            ['id' => 'kaz', 'internal_name' => 'Kazakhstan', 'backward_compatibility' => 'kz'],
            ['id' => 'ken', 'internal_name' => 'Kenya', 'backward_compatibility' => 'ke'],
            ['id' => 'kgz', 'internal_name' => 'Kyrgyzstan', 'backward_compatibility' => 'kg'],
            ['id' => 'khm', 'internal_name' => 'Cambodia', 'backward_compatibility' => 'kh'],
            ['id' => 'kir', 'internal_name' => 'Kiribati', 'backward_compatibility' => 'ki'],
            ['id' => 'kna', 'internal_name' => 'Saint Kitts and Nevis', 'backward_compatibility' => 'kn'],
            ['id' => 'kor', 'internal_name' => 'Korea, Republic of', 'backward_compatibility' => 'kr'],
            ['id' => 'kwt', 'internal_name' => 'Kuwait', 'backward_compatibility' => 'kw'],
            ['id' => 'lao', 'internal_name' => 'Lao People\'s Democratic Republic', 'backward_compatibility' => 'la'],
            ['id' => 'lbn', 'internal_name' => 'Lebanon', 'backward_compatibility' => 'lb'],
            ['id' => 'lbr', 'internal_name' => 'Liberia', 'backward_compatibility' => 'lr'],
            ['id' => 'lby', 'internal_name' => 'Libya', 'backward_compatibility' => 'ly'],
            ['id' => 'lca', 'internal_name' => 'Saint Lucia', 'backward_compatibility' => 'lc'],
            ['id' => 'lie', 'internal_name' => 'Liechtenstein', 'backward_compatibility' => 'li'],
            ['id' => 'lka', 'internal_name' => 'Sri Lanka', 'backward_compatibility' => 'lk'],
            ['id' => 'lso', 'internal_name' => 'Lesotho', 'backward_compatibility' => 'ls'],
            ['id' => 'ltu', 'internal_name' => 'Lithuania', 'backward_compatibility' => 'lt'],
            ['id' => 'lux', 'internal_name' => 'Luxembourg', 'backward_compatibility' => 'lu'],
            ['id' => 'lva', 'internal_name' => 'Latvia', 'backward_compatibility' => 'lv'],
            ['id' => 'mac', 'internal_name' => 'Macao', 'backward_compatibility' => 'mo'],
            ['id' => 'maf', 'internal_name' => 'Saint Martin (French part)', 'backward_compatibility' => 'mf'],
            ['id' => 'mar', 'internal_name' => 'Morocco', 'backward_compatibility' => 'ma'],
            ['id' => 'mco', 'internal_name' => 'Monaco', 'backward_compatibility' => 'mc'],
            ['id' => 'mda', 'internal_name' => 'Moldova, Republic of', 'backward_compatibility' => 'md'],
            ['id' => 'mdg', 'internal_name' => 'Madagascar', 'backward_compatibility' => 'mg'],
            ['id' => 'mdv', 'internal_name' => 'Maldives', 'backward_compatibility' => 'mv'],
            ['id' => 'mex', 'internal_name' => 'Mexico', 'backward_compatibility' => 'mx'],
            ['id' => 'mhl', 'internal_name' => 'Marshall Islands', 'backward_compatibility' => 'mh'],
            ['id' => 'mkd', 'internal_name' => 'North Macedonia', 'backward_compatibility' => 'mk'],
            ['id' => 'mli', 'internal_name' => 'Mali', 'backward_compatibility' => 'ml'],
            ['id' => 'mlt', 'internal_name' => 'Malta', 'backward_compatibility' => 'mt'],
            ['id' => 'mmr', 'internal_name' => 'Myanmar', 'backward_compatibility' => 'mm'],
            ['id' => 'mne', 'internal_name' => 'Montenegro', 'backward_compatibility' => 'me'],
            ['id' => 'mng', 'internal_name' => 'Mongolia', 'backward_compatibility' => 'mn'],
            ['id' => 'mnp', 'internal_name' => 'Northern Mariana Islands', 'backward_compatibility' => 'mp'],
            ['id' => 'moz', 'internal_name' => 'Mozambique', 'backward_compatibility' => 'mz'],
            ['id' => 'mrt', 'internal_name' => 'Mauritania', 'backward_compatibility' => 'mr'],
            ['id' => 'msr', 'internal_name' => 'Montserrat', 'backward_compatibility' => 'ms'],
            ['id' => 'mtq', 'internal_name' => 'Martinique', 'backward_compatibility' => 'mq'],
            ['id' => 'mus', 'internal_name' => 'Mauritius', 'backward_compatibility' => 'mu'],
            ['id' => 'mwi', 'internal_name' => 'Malawi', 'backward_compatibility' => 'mw'],
            ['id' => 'mys', 'internal_name' => 'Malaysia', 'backward_compatibility' => 'my'],
            ['id' => 'myt', 'internal_name' => 'Mayotte', 'backward_compatibility' => 'yt'],
            ['id' => 'nam', 'internal_name' => 'Namibia', 'backward_compatibility' => 'na'],
            ['id' => 'ncl', 'internal_name' => 'New Caledonia', 'backward_compatibility' => 'nc'],
            ['id' => 'ner', 'internal_name' => 'Niger', 'backward_compatibility' => 'ne'],
            ['id' => 'nfk', 'internal_name' => 'Norfolk Island', 'backward_compatibility' => 'nf'],
            ['id' => 'nga', 'internal_name' => 'Nigeria', 'backward_compatibility' => 'ng'],
            ['id' => 'nic', 'internal_name' => 'Nicaragua', 'backward_compatibility' => 'ni'],
            ['id' => 'niu', 'internal_name' => 'Niue', 'backward_compatibility' => 'nu'],
            ['id' => 'nld', 'internal_name' => 'Netherlands, Kingdom of the', 'backward_compatibility' => 'nl'],
            ['id' => 'nor', 'internal_name' => 'Norway', 'backward_compatibility' => 'no'],
            ['id' => 'npl', 'internal_name' => 'Nepal', 'backward_compatibility' => 'np'],
            ['id' => 'nru', 'internal_name' => 'Nauru', 'backward_compatibility' => 'nr'],
            ['id' => 'nzl', 'internal_name' => 'New Zealand', 'backward_compatibility' => 'nz'],
            ['id' => 'omn', 'internal_name' => 'Oman', 'backward_compatibility' => 'om'],
            ['id' => 'pak', 'internal_name' => 'Pakistan', 'backward_compatibility' => 'pk'],
            ['id' => 'pan', 'internal_name' => 'Panama', 'backward_compatibility' => 'pa'],
            ['id' => 'pcn', 'internal_name' => 'Pitcairn', 'backward_compatibility' => 'pn'],
            ['id' => 'per', 'internal_name' => 'Peru', 'backward_compatibility' => 'pe'],
            ['id' => 'phl', 'internal_name' => 'Philippines', 'backward_compatibility' => 'ph'],
            ['id' => 'plw', 'internal_name' => 'Palau', 'backward_compatibility' => 'pw'],
            ['id' => 'png', 'internal_name' => 'Papua New Guinea', 'backward_compatibility' => 'pg'],
            ['id' => 'pol', 'internal_name' => 'Poland', 'backward_compatibility' => 'pl'],
            ['id' => 'pri', 'internal_name' => 'Puerto Rico', 'backward_compatibility' => 'pr'],
            ['id' => 'prk', 'internal_name' => 'Korea, Democratic People\'s Republic of', 'backward_compatibility' => 'kp'],
            ['id' => 'prt', 'internal_name' => 'Portugal', 'backward_compatibility' => 'pt'],
            ['id' => 'pry', 'internal_name' => 'Paraguay', 'backward_compatibility' => 'py'],
            ['id' => 'pse', 'internal_name' => 'Palestine, State of', 'backward_compatibility' => 'ps'],
            ['id' => 'pyf', 'internal_name' => 'French Polynesia', 'backward_compatibility' => 'pf'],
            ['id' => 'qat', 'internal_name' => 'Qatar', 'backward_compatibility' => 'qa'],
            ['id' => 'reu', 'internal_name' => 'Réunion', 'backward_compatibility' => 're'],
            ['id' => 'rou', 'internal_name' => 'Romania', 'backward_compatibility' => 'ro'],
            ['id' => 'rus', 'internal_name' => 'Russian Federation', 'backward_compatibility' => 'ru'],
            ['id' => 'rwa', 'internal_name' => 'Rwanda', 'backward_compatibility' => 'rw'],
            ['id' => 'sau', 'internal_name' => 'Saudi Arabia', 'backward_compatibility' => 'sa'],
            ['id' => 'sdn', 'internal_name' => 'Sudan', 'backward_compatibility' => 'sd'],
            ['id' => 'sen', 'internal_name' => 'Senegal', 'backward_compatibility' => 'sn'],
            ['id' => 'sgp', 'internal_name' => 'Singapore', 'backward_compatibility' => 'sg'],
            ['id' => 'sgs', 'internal_name' => 'South Georgia and the South Sandwich Islands', 'backward_compatibility' => 'gs'],
            ['id' => 'shn', 'internal_name' => 'Saint Helena, Ascension and Tristan da Cunha', 'backward_compatibility' => 'sh'],
            ['id' => 'sjm', 'internal_name' => 'Svalbard and Jan Mayen', 'backward_compatibility' => 'sj'],
            ['id' => 'slb', 'internal_name' => 'Solomon Islands', 'backward_compatibility' => 'sb'],
            ['id' => 'sle', 'internal_name' => 'Sierra Leone', 'backward_compatibility' => 'sl'],
            ['id' => 'slv', 'internal_name' => 'El Salvador', 'backward_compatibility' => 'sv'],
            ['id' => 'smr', 'internal_name' => 'San Marino', 'backward_compatibility' => 'sm'],
            ['id' => 'som', 'internal_name' => 'Somalia', 'backward_compatibility' => 'so'],
            ['id' => 'spm', 'internal_name' => 'Saint Pierre and Miquelon', 'backward_compatibility' => 'pm'],
            ['id' => 'srb', 'internal_name' => 'Serbia', 'backward_compatibility' => 'rs'],
            ['id' => 'ssd', 'internal_name' => 'South Sudan', 'backward_compatibility' => 'ss'],
            ['id' => 'stp', 'internal_name' => 'Sao Tome and Principe', 'backward_compatibility' => 'st'],
            ['id' => 'sur', 'internal_name' => 'Suriname', 'backward_compatibility' => 'sr'],
            ['id' => 'svk', 'internal_name' => 'Slovakia', 'backward_compatibility' => 'sk'],
            ['id' => 'svn', 'internal_name' => 'Slovenia', 'backward_compatibility' => 'si'],
            ['id' => 'swe', 'internal_name' => 'Sweden', 'backward_compatibility' => 'se'],
            ['id' => 'swz', 'internal_name' => 'Eswatini', 'backward_compatibility' => 'sz'],
            ['id' => 'sxm', 'internal_name' => 'Sint Maarten (Dutch part)', 'backward_compatibility' => 'sx'],
            ['id' => 'syc', 'internal_name' => 'Seychelles', 'backward_compatibility' => 'sc'],
            ['id' => 'syr', 'internal_name' => 'Syrian Arab Republic', 'backward_compatibility' => 'sy'],
            ['id' => 'tca', 'internal_name' => 'Turks and Caicos Islands', 'backward_compatibility' => 'tc'],
            ['id' => 'tcd', 'internal_name' => 'Chad', 'backward_compatibility' => 'td'],
            ['id' => 'tgo', 'internal_name' => 'Togo', 'backward_compatibility' => 'tg'],
            ['id' => 'tha', 'internal_name' => 'Thailand', 'backward_compatibility' => 'th'],
            ['id' => 'tjk', 'internal_name' => 'Tajikistan', 'backward_compatibility' => 'tj'],
            ['id' => 'tkl', 'internal_name' => 'Tokelau', 'backward_compatibility' => 'tk'],
            ['id' => 'tkm', 'internal_name' => 'Turkmenistan', 'backward_compatibility' => 'tm'],
            ['id' => 'tls', 'internal_name' => 'Timor-Leste', 'backward_compatibility' => 'tl'],
            ['id' => 'ton', 'internal_name' => 'Tonga', 'backward_compatibility' => 'to'],
            ['id' => 'tto', 'internal_name' => 'Trinidad and Tobago', 'backward_compatibility' => 'tt'],
            ['id' => 'tun', 'internal_name' => 'Tunisia', 'backward_compatibility' => 'tn'],
            ['id' => 'tur', 'internal_name' => 'Türkiye', 'backward_compatibility' => 'tr'],
            ['id' => 'tuv', 'internal_name' => 'Tuvalu', 'backward_compatibility' => 'tv'],
            ['id' => 'twn', 'internal_name' => 'Taiwan, Province of China', 'backward_compatibility' => 'tw'],
            ['id' => 'tza', 'internal_name' => 'Tanzania, United Republic of', 'backward_compatibility' => 'tz'],
            ['id' => 'uga', 'internal_name' => 'Uganda', 'backward_compatibility' => 'ug'],
            ['id' => 'ukr', 'internal_name' => 'Ukraine', 'backward_compatibility' => 'ua'],
            ['id' => 'umi', 'internal_name' => 'United States Minor Outlying Islands', 'backward_compatibility' => 'um'],
            ['id' => 'ury', 'internal_name' => 'Uruguay', 'backward_compatibility' => 'uy'],
            ['id' => 'usa', 'internal_name' => 'United States of America', 'backward_compatibility' => 'us'],
            ['id' => 'uzb', 'internal_name' => 'Uzbekistan', 'backward_compatibility' => 'uz'],
            ['id' => 'vat', 'internal_name' => 'Holy See', 'backward_compatibility' => 'va'],
            ['id' => 'vct', 'internal_name' => 'Saint Vincent and the Grenadines', 'backward_compatibility' => 'vc'],
            ['id' => 'ven', 'internal_name' => 'Venezuela, Bolivarian Republic of', 'backward_compatibility' => 've'],
            ['id' => 'vgb', 'internal_name' => 'Virgin Islands (British)', 'backward_compatibility' => 'vg'],
            ['id' => 'vir', 'internal_name' => 'Virgin Islands (U.S.)', 'backward_compatibility' => 'vi'],
            ['id' => 'vnm', 'internal_name' => 'Viet Nam', 'backward_compatibility' => 'vn'],
            ['id' => 'wlf', 'internal_name' => 'Wallis and Futuna', 'backward_compatibility' => 'wf'],
            ['id' => 'wsm', 'internal_name' => 'Samoa', 'backward_compatibility' => 'ws'],
            ['id' => 'yem', 'internal_name' => 'Yemen', 'backward_compatibility' => 'ye'],
            ['id' => 'zaf', 'internal_name' => 'South Africa', 'backward_compatibility' => 'za'],
            ['id' => 'zmb', 'internal_name' => 'Zambia', 'backward_compatibility' => 'zm'],
            ['id' => 'zwe', 'internal_name' => 'Zimbabwe', 'backward_compatibility' => 'zw'],
        ];

        foreach ($countries as $country) {
            Country::create($country);
        }

    }
}
