<?php

namespace Database\Seeders;

use App\Models\Language;
use Illuminate\Database\Seeder;

class LanguageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $languages = [
            ['id' => 'abk', 'internal_name' => 'Abkhazian', 'backward_compatibility' => 'ab'],
            ['id' => 'aar', 'internal_name' => 'Afar', 'backward_compatibility' => 'aa'],
            ['id' => 'afr', 'internal_name' => 'Afrikaans', 'backward_compatibility' => 'af'],
            ['id' => 'aka', 'internal_name' => 'Akan', 'backward_compatibility' => 'ak'],
            ['id' => 'amh', 'internal_name' => 'Amharic', 'backward_compatibility' => 'am'],
            ['id' => 'ara', 'internal_name' => 'Arabic', 'backward_compatibility' => 'ar'],
            ['id' => 'arg', 'internal_name' => 'Aragonese', 'backward_compatibility' => 'an'],
            ['id' => 'asm', 'internal_name' => 'Assamese', 'backward_compatibility' => 'as'],
            ['id' => 'ava', 'internal_name' => 'Avaric', 'backward_compatibility' => 'av'],
            ['id' => 'ave', 'internal_name' => 'Avestan', 'backward_compatibility' => 'ae'],
            ['id' => 'aym', 'internal_name' => 'Aymara', 'backward_compatibility' => 'ay'],
            ['id' => 'aze', 'internal_name' => 'Azerbaijani', 'backward_compatibility' => 'az'],
            ['id' => 'bak', 'internal_name' => 'Bashkir', 'backward_compatibility' => 'ba'],
            ['id' => 'bam', 'internal_name' => 'Bambara', 'backward_compatibility' => 'bm'],
            ['id' => 'bel', 'internal_name' => 'Belarusian', 'backward_compatibility' => 'be'],
            ['id' => 'ben', 'internal_name' => 'Bengali', 'backward_compatibility' => 'bn'],
            ['id' => 'bis', 'internal_name' => 'Bislama', 'backward_compatibility' => 'bi'],
            ['id' => 'bod', 'internal_name' => 'Tibetan', 'backward_compatibility' => 'bo'],
            ['id' => 'bos', 'internal_name' => 'Bosnian', 'backward_compatibility' => 'bs'],
            ['id' => 'bre', 'internal_name' => 'Breton', 'backward_compatibility' => 'br'],
            ['id' => 'bul', 'internal_name' => 'Bulgarian', 'backward_compatibility' => 'bg'],
            ['id' => 'cat', 'internal_name' => 'Catalan', 'backward_compatibility' => 'ca'],
            ['id' => 'ces', 'internal_name' => 'Czech', 'backward_compatibility' => 'cs'],
            ['id' => 'chu', 'internal_name' => 'Church Slavic', 'backward_compatibility' => 'cu'],
            ['id' => 'chv', 'internal_name' => 'Chuvash', 'backward_compatibility' => 'cv'],
            ['id' => 'cor', 'internal_name' => 'Cornish', 'backward_compatibility' => 'kw'],
            ['id' => 'cos', 'internal_name' => 'Corsican', 'backward_compatibility' => 'co'],
            ['id' => 'cre', 'internal_name' => 'Cree', 'backward_compatibility' => 'cr'],
            ['id' => 'cym', 'internal_name' => 'Welsh', 'backward_compatibility' => 'cy'],
            ['id' => 'dan', 'internal_name' => 'Danish', 'backward_compatibility' => 'da'],
            ['id' => 'deu', 'internal_name' => 'Deutsch', 'backward_compatibility' => 'de'],
            ['id' => 'div', 'internal_name' => 'Divehi', 'backward_compatibility' => 'dv'],
            ['id' => 'dzo', 'internal_name' => 'Dzongkha', 'backward_compatibility' => 'dz'],
            ['id' => 'ell', 'internal_name' => 'Greek', 'backward_compatibility' => 'el'],
            ['id' => 'eng', 'internal_name' => 'English', 'backward_compatibility' => 'en'],
            ['id' => 'epo', 'internal_name' => 'Esperanto', 'backward_compatibility' => 'eo'],
            ['id' => 'est', 'internal_name' => 'Estonian', 'backward_compatibility' => 'et'],
            ['id' => 'eus', 'internal_name' => 'Basque', 'backward_compatibility' => 'eu'],
            ['id' => 'fas', 'internal_name' => 'Persian', 'backward_compatibility' => 'fa'],
            ['id' => 'fij', 'internal_name' => 'Fijian', 'backward_compatibility' => 'fj'],
            ['id' => 'fin', 'internal_name' => 'Finnish', 'backward_compatibility' => 'fi'],
            ['id' => 'fra', 'internal_name' => 'Français', 'backward_compatibility' => 'fr'],
            ['id' => 'fry', 'internal_name' => 'Western Frisian', 'backward_compatibility' => 'fy'],
            ['id' => 'ful', 'internal_name' => 'Fulah', 'backward_compatibility' => 'ff'],
            ['id' => 'gla', 'internal_name' => 'Scottish Gaelic', 'backward_compatibility' => 'gd'],
            ['id' => 'gle', 'internal_name' => 'Irish', 'backward_compatibility' => 'ga'],
            ['id' => 'glg', 'internal_name' => 'Galician', 'backward_compatibility' => 'gl'],
            ['id' => 'glv', 'internal_name' => 'Manx', 'backward_compatibility' => 'gv'],
            ['id' => 'grn', 'internal_name' => 'Guarani', 'backward_compatibility' => 'gn'],
            ['id' => 'guj', 'internal_name' => 'Gujarati', 'backward_compatibility' => 'gu'],
            ['id' => 'hat', 'internal_name' => 'Haitian', 'backward_compatibility' => 'ht'],
            ['id' => 'hau', 'internal_name' => 'Hausa', 'backward_compatibility' => 'ha'],
            ['id' => 'hbs', 'internal_name' => 'Serbo-Croatian', 'backward_compatibility' => 'sh'],
            ['id' => 'heb', 'internal_name' => 'Hebrew', 'backward_compatibility' => 'he'],
            ['id' => 'her', 'internal_name' => 'Herero', 'backward_compatibility' => 'hz'],
            ['id' => 'hin', 'internal_name' => 'Hindi', 'backward_compatibility' => 'hi'],
            ['id' => 'hmo', 'internal_name' => 'Hiri Motu', 'backward_compatibility' => 'ho'],
            ['id' => 'hrv', 'internal_name' => 'Croatian', 'backward_compatibility' => 'hr'],
            ['id' => 'hun', 'internal_name' => 'Hungarian', 'backward_compatibility' => 'hu'],
            ['id' => 'hye', 'internal_name' => 'Armenian', 'backward_compatibility' => 'hy'],
            ['id' => 'ibo', 'internal_name' => 'Igbo', 'backward_compatibility' => 'ig'],
            ['id' => 'ido', 'internal_name' => 'Ido', 'backward_compatibility' => 'io'],
            ['id' => 'iii', 'internal_name' => 'Sichuan Yi', 'backward_compatibility' => 'ii'],
            ['id' => 'iku', 'internal_name' => 'Inuktitut', 'backward_compatibility' => 'iu'],
            ['id' => 'ile', 'internal_name' => 'Interlingue', 'backward_compatibility' => 'ie'],
            ['id' => 'ina', 'internal_name' => 'Interlingua', 'backward_compatibility' => 'ia'],
            ['id' => 'ind', 'internal_name' => 'Indonesian', 'backward_compatibility' => 'id'],
            ['id' => 'ipk', 'internal_name' => 'Inupiaq', 'backward_compatibility' => 'ik'],
            ['id' => 'isl', 'internal_name' => 'Icelandic', 'backward_compatibility' => 'is'],
            ['id' => 'ita', 'internal_name' => 'Italiano', 'backward_compatibility' => 'it'],
            ['id' => 'jav', 'internal_name' => 'Javanese', 'backward_compatibility' => 'jv'],
            ['id' => 'jpn', 'internal_name' => 'Japanese', 'backward_compatibility' => 'ja'],
            ['id' => 'kal', 'internal_name' => 'Kalaallisut', 'backward_compatibility' => 'kl'],
            ['id' => 'kan', 'internal_name' => 'Kannada', 'backward_compatibility' => 'kn'],
            ['id' => 'kas', 'internal_name' => 'Kashmiri', 'backward_compatibility' => 'ks'],
            ['id' => 'kat', 'internal_name' => 'Georgian', 'backward_compatibility' => 'ka'],
            ['id' => 'kau', 'internal_name' => 'Kanuri', 'backward_compatibility' => 'kr'],
            ['id' => 'kaz', 'internal_name' => 'Kazakh', 'backward_compatibility' => 'kk'],
            ['id' => 'khm', 'internal_name' => 'Central Khmer', 'backward_compatibility' => 'km'],
            ['id' => 'kik', 'internal_name' => 'Kikuyu', 'backward_compatibility' => 'ki'],
            ['id' => 'kin', 'internal_name' => 'Kinyarwanda', 'backward_compatibility' => 'rw'],
            ['id' => 'kir', 'internal_name' => 'Kirghiz', 'backward_compatibility' => 'ky'],
            ['id' => 'kom', 'internal_name' => 'Komi', 'backward_compatibility' => 'kv'],
            ['id' => 'kon', 'internal_name' => 'Kongo', 'backward_compatibility' => 'kg'],
            ['id' => 'kor', 'internal_name' => 'Korean', 'backward_compatibility' => 'ko'],
            ['id' => 'kua', 'internal_name' => 'Kuanyama', 'backward_compatibility' => 'kj'],
            ['id' => 'kur', 'internal_name' => 'Kurdish', 'backward_compatibility' => 'ku'],
            ['id' => 'lao', 'internal_name' => 'Lao', 'backward_compatibility' => 'lo'],
            ['id' => 'lat', 'internal_name' => 'Latin', 'backward_compatibility' => 'la'],
            ['id' => 'lav', 'internal_name' => 'Latvian', 'backward_compatibility' => 'lv'],
            ['id' => 'lim', 'internal_name' => 'Limburgan', 'backward_compatibility' => 'li'],
            ['id' => 'lin', 'internal_name' => 'Lingala', 'backward_compatibility' => 'ln'],
            ['id' => 'lit', 'internal_name' => 'Lithuanian', 'backward_compatibility' => 'lt'],
            ['id' => 'ltz', 'internal_name' => 'Luxembourgish', 'backward_compatibility' => 'lb'],
            ['id' => 'lub', 'internal_name' => 'Luba-Katanga', 'backward_compatibility' => 'lu'],
            ['id' => 'lug', 'internal_name' => 'Ganda', 'backward_compatibility' => 'lg'],
            ['id' => 'mah', 'internal_name' => 'Marshallese', 'backward_compatibility' => 'mh'],
            ['id' => 'mal', 'internal_name' => 'Malayalam', 'backward_compatibility' => 'ml'],
            ['id' => 'mar', 'internal_name' => 'Marathi', 'backward_compatibility' => 'mr'],
            ['id' => 'mkd', 'internal_name' => 'Macedonian', 'backward_compatibility' => 'mk'],
            ['id' => 'mlg', 'internal_name' => 'Malagasy', 'backward_compatibility' => 'mg'],
            ['id' => 'mlt', 'internal_name' => 'Maltese', 'backward_compatibility' => 'mt'],
            ['id' => 'mon', 'internal_name' => 'Mongolian', 'backward_compatibility' => 'mn'],
            ['id' => 'mri', 'internal_name' => 'Maori', 'backward_compatibility' => 'mi'],
            ['id' => 'msa', 'internal_name' => 'Malay', 'backward_compatibility' => 'ms'],
            ['id' => 'mya', 'internal_name' => 'Burmese', 'backward_compatibility' => 'my'],
            ['id' => 'nau', 'internal_name' => 'Nauru', 'backward_compatibility' => 'na'],
            ['id' => 'nav', 'internal_name' => 'Navajo', 'backward_compatibility' => 'nv'],
            ['id' => 'nbl', 'internal_name' => 'South Ndebele', 'backward_compatibility' => 'nr'],
            ['id' => 'nde', 'internal_name' => 'North Ndebele', 'backward_compatibility' => 'nd'],
            ['id' => 'ndo', 'internal_name' => 'Ndonga', 'backward_compatibility' => 'ng'],
            ['id' => 'nep', 'internal_name' => 'Nepali', 'backward_compatibility' => 'ne'],
            ['id' => 'nld', 'internal_name' => 'Dutch', 'backward_compatibility' => 'nl'],
            ['id' => 'nno', 'internal_name' => 'Norwegian Nynorsk', 'backward_compatibility' => 'nn'],
            ['id' => 'nob', 'internal_name' => 'Norwegian Bokmål', 'backward_compatibility' => 'nb'],
            ['id' => 'nor', 'internal_name' => 'Norwegian', 'backward_compatibility' => 'no'],
            ['id' => 'nya', 'internal_name' => 'Chichewa', 'backward_compatibility' => 'ny'],
            ['id' => 'oci', 'internal_name' => 'Occitan', 'backward_compatibility' => 'oc'],
            ['id' => 'oji', 'internal_name' => 'Ojibwa', 'backward_compatibility' => 'oj'],
            ['id' => 'ori', 'internal_name' => 'Oriya', 'backward_compatibility' => 'or'],
            ['id' => 'orm', 'internal_name' => 'Oromo', 'backward_compatibility' => 'om'],
            ['id' => 'oss', 'internal_name' => 'Ossetian', 'backward_compatibility' => 'os'],
            ['id' => 'pan', 'internal_name' => 'Panjabi', 'backward_compatibility' => 'pa'],
            ['id' => 'pli', 'internal_name' => 'Pali', 'backward_compatibility' => 'pi'],
            ['id' => 'pol', 'internal_name' => 'Polish', 'backward_compatibility' => 'pl'],
            ['id' => 'pus', 'internal_name' => 'Pashto', 'backward_compatibility' => 'ps'],
            ['id' => 'que', 'internal_name' => 'Quechua', 'backward_compatibility' => 'qu'],
            ['id' => 'roh', 'internal_name' => 'Romansh', 'backward_compatibility' => 'rm'],
            ['id' => 'ron', 'internal_name' => 'Romanian', 'backward_compatibility' => 'ro'],
            ['id' => 'run', 'internal_name' => 'Rundi', 'backward_compatibility' => 'rn'],
            ['id' => 'rus', 'internal_name' => 'Russian', 'backward_compatibility' => 'ru'],
            ['id' => 'sag', 'internal_name' => 'Sango', 'backward_compatibility' => 'sg'],
            ['id' => 'san', 'internal_name' => 'Sanskrit', 'backward_compatibility' => 'sa'],
            ['id' => 'sin', 'internal_name' => 'Sinhala', 'backward_compatibility' => 'si'],
            ['id' => 'slk', 'internal_name' => 'Slovak', 'backward_compatibility' => 'sk'],
            ['id' => 'slv', 'internal_name' => 'Slovenian', 'backward_compatibility' => 'sl'],
            ['id' => 'sme', 'internal_name' => 'Northern Sami', 'backward_compatibility' => 'se'],
            ['id' => 'smo', 'internal_name' => 'Samoan', 'backward_compatibility' => 'sm'],
            ['id' => 'sna', 'internal_name' => 'Shona', 'backward_compatibility' => 'sn'],
            ['id' => 'snd', 'internal_name' => 'Sindhi', 'backward_compatibility' => 'sd'],
            ['id' => 'som', 'internal_name' => 'Somali', 'backward_compatibility' => 'so'],
            ['id' => 'sot', 'internal_name' => 'Southern Sotho', 'backward_compatibility' => 'st'],
            ['id' => 'spa', 'internal_name' => 'Español', 'backward_compatibility' => 'es'],
            ['id' => 'sqi', 'internal_name' => 'Albanian', 'backward_compatibility' => 'sq'],
            ['id' => 'srd', 'internal_name' => 'Sardinian', 'backward_compatibility' => 'sc'],
            ['id' => 'srp', 'internal_name' => 'Serbian', 'backward_compatibility' => 'sr'],
            ['id' => 'ssw', 'internal_name' => 'Swati', 'backward_compatibility' => 'ss'],
            ['id' => 'sun', 'internal_name' => 'Sundanese', 'backward_compatibility' => 'su'],
            ['id' => 'swa', 'internal_name' => 'Swahili', 'backward_compatibility' => 'sw'],
            ['id' => 'swe', 'internal_name' => 'Swedish', 'backward_compatibility' => 'sv'],
            ['id' => 'tah', 'internal_name' => 'Tahitian', 'backward_compatibility' => 'ty'],
            ['id' => 'tam', 'internal_name' => 'Tamil', 'backward_compatibility' => 'ta'],
            ['id' => 'tat', 'internal_name' => 'Tatar', 'backward_compatibility' => 'tt'],
            ['id' => 'tel', 'internal_name' => 'Telugu', 'backward_compatibility' => 'te'],
            ['id' => 'tgk', 'internal_name' => 'Tajik', 'backward_compatibility' => 'tg'],
            ['id' => 'tgl', 'internal_name' => 'Tagalog', 'backward_compatibility' => 'tl'],
            ['id' => 'tha', 'internal_name' => 'Thai', 'backward_compatibility' => 'th'],
            ['id' => 'tir', 'internal_name' => 'Tigrinya', 'backward_compatibility' => 'ti'],
            ['id' => 'ton', 'internal_name' => 'Tonga', 'backward_compatibility' => 'to'],
            ['id' => 'tsn', 'internal_name' => 'Tswana', 'backward_compatibility' => 'tn'],
            ['id' => 'tso', 'internal_name' => 'Tsonga', 'backward_compatibility' => 'ts'],
            ['id' => 'tuk', 'internal_name' => 'Turkmen', 'backward_compatibility' => 'tk'],
            ['id' => 'tur', 'internal_name' => 'Turkish', 'backward_compatibility' => 'tr'],
            ['id' => 'twi', 'internal_name' => 'Twi', 'backward_compatibility' => 'tw'],
            ['id' => 'uig', 'internal_name' => 'Uighur', 'backward_compatibility' => 'ug'],
            ['id' => 'ukr', 'internal_name' => 'Ukrainian', 'backward_compatibility' => 'uk'],
            ['id' => 'urd', 'internal_name' => 'Urdu', 'backward_compatibility' => 'ur'],
            ['id' => 'uzb', 'internal_name' => 'Uzbek', 'backward_compatibility' => 'uz'],
            ['id' => 'ven', 'internal_name' => 'Venda', 'backward_compatibility' => 've'],
            ['id' => 'vie', 'internal_name' => 'Vietnamese', 'backward_compatibility' => 'vi'],
            ['id' => 'vol', 'internal_name' => 'Volapük', 'backward_compatibility' => 'vo'],
            ['id' => 'wln', 'internal_name' => 'Walloon', 'backward_compatibility' => 'wa'],
            ['id' => 'wol', 'internal_name' => 'Wolof', 'backward_compatibility' => 'wo'],
            ['id' => 'xho', 'internal_name' => 'Xhosa', 'backward_compatibility' => 'xh'],
            ['id' => 'yid', 'internal_name' => 'Yiddish', 'backward_compatibility' => 'yi'],
            ['id' => 'yor', 'internal_name' => 'Yoruba', 'backward_compatibility' => 'yo'],
            ['id' => 'zha', 'internal_name' => 'Zhuang', 'backward_compatibility' => 'za'],
            ['id' => 'zul', 'internal_name' => 'Zulu', 'backward_compatibility' => 'zu'],
        ];

        foreach ($languages as $language) {
            Language::create($language);
        }
    }
}
