name: 'Detect Environment'
description: 'Detects whether the workflow is running in GitHub Actions or act (local testing)'

outputs:
  is_act:
    description: 'Whether running in act (true/false)'
    value: ${{ steps.detect.outputs.is_act }}
  is_github:
    description: 'Whether running on GitHub Actions (true/false)'
    value: ${{ steps.detect.outputs.is_github }}
  environment:
    description: 'Environment name (github or act)'
    value: ${{ steps.detect.outputs.environment }}

runs:
  using: "composite"
  steps:
    - name: "Detect environment"
      id: detect
      shell: bash
      run: |
        if [ -n "$ACT" ]; then
          echo "is_act=true" >> $GITHUB_OUTPUT
          echo "is_github=false" >> $GITHUB_OUTPUT
          echo "environment=act" >> $GITHUB_OUTPUT
          echo ":gear: Running in 'act' (local testing mode)"
        else
          echo "is_act=false" >> $GITHUB_OUTPUT
          echo "is_github=true" >> $GITHUB_OUTPUT
          echo "environment=github" >> $GITHUB_OUTPUT
          echo ":white_check_mark: Running on GitHub Actions"
        fi
