name: 'Generate API Client'
description: 'Generates TypeScript API client from OpenAPI specification'

outputs:
  has-changes:
    description: 'Whether significant changes were detected in the API client'
    value: ${{ steps.generate.outputs.has-changes }}

inputs:
  openapi_spec_path:
    description: 'Path to the OpenAPI specification file'
    required: true
    default: 'docs/_openapi/api.json'
  output_directory:
    description: 'Output directory for generated client'
    required: true
    default: 'api-client'

runs:
  using: "composite"
  steps:
    - name: "Setup > PHP"
      uses: shivammathur/setup-php@v2
      with:
        extensions: fileinfo, zip, sqlite3, pdo_sqlite, gd, exif

    - name: "Setup > Composer > Install Dependencies"
      shell: bash
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: ':memory:'
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: "Generate TypeScript client"
      id: generate
      shell: bash
      run: |
        echo "::notice:: :gear: Calculate next API client version (auto-increment strategy)"
        EXISTING_PACKAGE="api-client/package.json"
        NEW_VERSION="1.0.1"
        if [ -f "$EXISTING_PACKAGE" ]; then
          EXISTING_VERSION=$(jq -r '.version' "$EXISTING_PACKAGE")
          echo "Current version: $EXISTING_VERSION"
          # Parse version (remove any pre-release and build metadata for parsing)
          if [[ $EXISTING_VERSION =~ ^([0-9]+)\.([0-9]+)\.([0-9]+) ]]; then
            MAJOR="${BASH_REMATCH[1]}"
            MINOR="${BASH_REMATCH[2]}"
            PATCH="${BASH_REMATCH[3]}"
            PATCH=$((PATCH + 1))
            NEW_VERSION="${MAJOR}.${MINOR}.${PATCH}"
          fi
        fi
        # Add pre-release identifier and timestamp (MMDD.HHMM)
        TIMESTAMP=$(date -u +"%m%d.%H%M")
        FULL_VERSION="${NEW_VERSION}-dev.${TIMESTAMP}"
        echo ":gear: New version: $FULL_VERSION"

        echo "::notice:: :gear: Preserve previous client"
        if [ -d "${{ inputs.output_directory }}" ]; then
          echo "::notice:: :gear: Preserve previous client"
          OLD_DIR="${{ inputs.output_directory }}_old"
          rm -rf "$OLD_DIR"
          mv "${{ inputs.output_directory }}" "$OLD_DIR"

          echo "::warning:: $OLD_DIR"
          ls -lRa "$OLD_DIR"
        else
          echo "::notice:: :x: THE DIRECTORY DID NOT EXIST"
        fi
        mkdir -p ${{ inputs.output_directory }}

        echo "::notice:: :gear: Generate the api-client"
        npx @openapitools/openapi-generator-cli generate \
          -i ${{ inputs.openapi_spec_path }} \
          -g typescript-axios \
          -o ${{ inputs.output_directory }} >/dev/null || cat

        echo "::warning:: ${{ inputs.output_directory }}"
        ls -lRa "${{ inputs.output_directory }}"

        echo "::notice:: :gear: Create api.json"
        php artisan scramble:export --path=docs/_openapi/api.json --ansi

        echo "::notice:: :gear: Create README.md"
        cp ./.github/templates/api-client/README.md ${{ inputs.output_directory }}/
        
        echo "::notice:: :gear: Create package.json"
        jq --arg ver "$FULL_VERSION" '.version = $ver' ./.github/templates/api-client/package.json > ${{ inputs.output_directory }}/package.json

        echo "::notice:: :gear: Compare old and new clients"
        if [ -d "$OLD_DIR" ]; then
            # Compare only essential files in top directory
            CORE_FILES="api.ts base.ts common.ts configuration.ts index.ts"
            HAS_CHANGES=0

            echo "::group::Checking core files"
            for file in $CORE_FILES; do
                if ! cmp -s "$OLD_DIR/$file" "${{ inputs.output_directory }}/$file"; then
                    echo "Changed: $file"
                    HAS_CHANGES=1
                fi
            done
            echo "::endgroup::"

            if [ $HAS_CHANGES -eq 1 ]; then
                echo ":white_check_mark: API client has significant changes"
                echo "has-changes=true" >> $GITHUB_OUTPUT
            else
                echo ":x: No API changes detected"
                echo "has-changes=false" >> $GITHUB_OUTPUT
            fi
        else
            echo ":white_check_mark: First time generation"
            echo "has-changes=true" >> $GITHUB_OUTPUT
        fi

        # Always cleanup at the end
        rm -rf "$OLD_DIR"
