name: 'Generate API Client'
description: 'Generates TypeScript API client from OpenAPI specification'

outputs:
  has-changes:
    description: 'Whether significant changes were detected in the API client'
    value: ${{ steps.generate.outputs.has-changes }}

inputs:
  openapi_spec_path:
    description: 'Path to the OpenAPI specification file'
    required: true
    default: 'docs/_openapi/api.json'
  output_directory:
    description: 'Output directory for generated client'
    required: true
    default: 'api-client'

runs:
  using: "composite"
  steps:
    - name: "Generate TypeScript client"
      id: generate
      shell: bash
      run: |
        # Calculate next API client version (auto-increment strategy)
        EXISTING_PACKAGE="api-client/package.json"
        NEW_VERSION="1.0.1"
        if [ -f "$EXISTING_PACKAGE" ]; then
          EXISTING_VERSION=$(jq -r '.version' "$EXISTING_PACKAGE")
          echo "Current version: $EXISTING_VERSION"
          # Parse version (remove any pre-release and build metadata for parsing)
          if [[ $EXISTING_VERSION =~ ^([0-9]+)\.([0-9]+)\.([0-9]+) ]]; then
            MAJOR="${BASH_REMATCH[1]}"
            MINOR="${BASH_REMATCH[2]}"
            PATCH="${BASH_REMATCH[3]}"
            PATCH=$((PATCH + 1))
            NEW_VERSION="${MAJOR}.${MINOR}.${PATCH}"
          fi
        fi
        # Add pre-release identifier and build metadata
        PRE_RELEASE="dev"
        BUILD_METADATA=$(date -u +"%Y%m%d.%H%M")
        FULL_VERSION="${NEW_VERSION}-${PRE_RELEASE}+${BUILD_METADATA}"
        echo ":gear: New version: $FULL_VERSION"

        # Remove previous client
        rm -rf ${{ inputs.output_directory }}
        mkdir -p ${{ inputs.output_directory }}

        # Create README.md and package.json with updated version from templates
        cp ./.github/templates/api-client/README.md ${{ inputs.output_directory }}/
        # Update version in package.json template
        jq --arg ver "$FULL_VERSION" '.version = $ver' ./.github/templates/api-client/package.json > ${{ inputs.output_directory }}/package.json

        # Generate new client
        npx @openapitools/openapi-generator-cli generate \
          -i ${{ inputs.openapi_spec_path }} \
          -g typescript-axios \
          -o ${{ inputs.output_directory }}

        # Get list of changed files
        CHANGED_FILES=$(git diff --name-only | grep '^${{ inputs.output_directory }}/' || true)
        
        if [ -z "$CHANGED_FILES" ]; then
          echo "No changes detected in ${{ inputs.output_directory }}"
          echo "has-changes=false" >> $GITHUB_OUTPUT
          exit 0
        fi
        
        # Filter out the FILES metadata file that always change
        SIGNIFICANT_CHANGES=$(echo "$CHANGED_FILES" | grep -v -E '^${{ inputs.output_directory }}/(FILES|README.md|package.json)$' || true)
        
        if [ -z "$SIGNIFICANT_CHANGES" ]; then
          echo ":x: No changes detected"
          echo "has-changes=false" >> $GITHUB_OUTPUT
        else
          echo ":white_check_mark: API client has significant changes"
          echo "has-changes=true" >> $GITHUB_OUTPUT
        fi
