name: 'Generate API Client'
description: 'Generates TypeScript API client from OpenAPI specification'

inputs:
  openapi_spec_path:
    description: 'Path to the OpenAPI specification file'
    required: true
    default: 'docs/_openapi/api.json'
  output_directory:
    description: 'Output directory for generated client'
    required: true
    default: 'api-client'
  package_name:
    description: 'Package name'
    required: true
  version:
    description: 'Package version'
    required: true
  package_main:
    description: 'Main entry point'
    required: true
  package_types:
    description: 'TypeScript definitions entry point'
    required: true
  package_description:
    description: 'Package description'
    required: true
  package_repository:
    description: 'Repository URL'
    required: true
  package_author:
    description: 'Package author'
    required: true
  package_license:
    description: 'Package license'
    required: true

runs:
  using: "composite"
  steps:
    - name: "Generate TypeScript client"
      shell: bash
      run: |
        npx @openapitools/openapi-generator-cli generate \
          -i ${{ inputs.openapi_spec_path }} \
          -g typescript-axios \
          -o ${{ inputs.output_directory }}

    - name: "Create package.json"
      shell: bash
      run: |
        cat > ${{ inputs.output_directory }}/package.json << EOF
        {
          "name": "${{ inputs.package_name }}",
          "version": "${{ inputs.version }}",
          "main": "${{ inputs.package_main }}",
          "types": "${{ inputs.package_types }}",
          "description": "${{ inputs.package_description }}",
          "repository": {
            "type": "git",
            "url": "git+${{ inputs.package_repository }}.git"
          },
          "author": "${{ inputs.package_author }}",
          "license": "${{ inputs.package_license }}"
        }
        EOF

    - name: "Create README.md"
      shell: bash
      run: |
        cat > ${{ inputs.output_directory }}/README.md << 'EOF'
        # ${{ inputs.package_name }}

        This is a generated TypeScript client for the inventory-app API using OpenAPI and Axios.

        ## Installation

        ```shell
        npm install ${{ inputs.package_name }}
        ```

        ## Usage Example

        ```typescript
        import { Configuration, DefaultApi } from '${{ inputs.package_name }}';

        const api = new DefaultApi(new Configuration({ basePath: 'https://your.api.url' }));
        api.addressIndex().then(response => console.log(response.data));
        ```

        ## Versioning

        This client uses automatic versioning to track API changes:
        - **Auto-increment**: Patch version increases with each generation
        - **Development versions**: Include `-dev` suffix and build metadata
        - **API changes**: When the OpenAPI spec changes, a new version is generated

        To check for updates:
        ```shell
        npm outdated ${{ inputs.package_name }}
        ```

        ## Publishing

        The package is automatically published to GitHub Packages when changes are detected.

        ---
        This client is auto-generated. For customizations, edit the OpenAPI spec and regenerate.
        EOF
