name: 'Generate OpenAPI Specification'
description: 'Generates the OpenAPI specification using Laravel Scramble'

runs:
  using: "composite"
  steps:
    - name: "Setup > PHP"
      uses: shivammathur/setup-php@v2
      with:
        extensions: fileinfo, zip, sqlite3, pdo_sqlite, gd, exif

    - name: "Setup > Composer > Install Dependencies"
      shell: bash
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: ':memory:'
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: "Build > OpenAPI > Create output directory"
      shell: bash
      run: mkdir -p docs/_openapi

    - name: "Build > OpenAPI > Export specification"
      shell: bash
      run: php artisan scramble:export --path=docs/_openapi/api.json --ansi
