name: 'Calculate API Client Version'
description: 'Calculates the next version for the API client package'

outputs:
  version:
    description: 'Full version with pre-release and build metadata'
    value: ${{ steps.calculate.outputs.version }}
  base_version:
    description: 'Base semantic version without pre-release'
    value: ${{ steps.calculate.outputs.base_version }}
  package_name:
    description: 'Package name'
    value: ${{ steps.calculate.outputs.package_name }}
  package_main:
    description: 'Main entry point'
    value: ${{ steps.calculate.outputs.package_main }}
  package_types:
    description: 'TypeScript definitions entry point'
    value: ${{ steps.calculate.outputs.package_types }}
  package_description:
    description: 'Package description'
    value: ${{ steps.calculate.outputs.package_description }}
  package_repository:
    description: 'Repository URL'
    value: ${{ steps.calculate.outputs.package_repository }}
  package_author:
    description: 'Package author'
    value: ${{ steps.calculate.outputs.package_author }}
  package_license:
    description: 'Package license'
    value: ${{ steps.calculate.outputs.package_license }}

runs:
  using: "composite"
  steps:
    - name: "Calculate version"
      id: calculate
      shell: bash
      run: |
        # Configuration (extracted from api-client-config.psd1)
        BASE_VERSION="1.0.1"
        PACKAGE_NAME="@metanull/inventory-app-api-client"
        PACKAGE_MAIN="index.js"
        PACKAGE_TYPES="index.d.ts"
        PACKAGE_DESCRIPTION="TypeScript-Axios client for inventory-app API"
        PACKAGE_REPOSITORY="https://github.com/metanull/inventory-app"
        PACKAGE_AUTHOR="Pascal Havelange"
        PACKAGE_LICENSE="MIT"
        
        # Version calculation (auto-increment strategy)
        EXISTING_PACKAGE="api-client/package.json"
        
        if [ -f "$EXISTING_PACKAGE" ]; then
          # Extract existing version using jq
          EXISTING_VERSION=$(jq -r '.version' "$EXISTING_PACKAGE")
          echo "Found existing version: $EXISTING_VERSION"
          
          # Parse version (remove any pre-release and build metadata for parsing)
          if [[ $EXISTING_VERSION =~ ^([0-9]+)\.([0-9]+)\.([0-9]+) ]]; then
            MAJOR="${BASH_REMATCH[1]}"
            MINOR="${BASH_REMATCH[2]}"
            PATCH="${BASH_REMATCH[3]}"
            
            # Increment patch version
            PATCH=$((PATCH + 1))
            NEW_VERSION="${MAJOR}.${MINOR}.${PATCH}"
          else
            NEW_VERSION="$BASE_VERSION"
          fi
        else
          NEW_VERSION="$BASE_VERSION"
        fi
        
        # Add pre-release identifier and build metadata
        PRE_RELEASE="dev"
        BUILD_METADATA=$(date -u +"%Y%m%d.%H%M")
        FULL_VERSION="${NEW_VERSION}-${PRE_RELEASE}+${BUILD_METADATA}"
        
        echo "Generated version: $FULL_VERSION"
        echo "version=$FULL_VERSION" >> $GITHUB_OUTPUT
        echo "base_version=$NEW_VERSION" >> $GITHUB_OUTPUT
        echo "package_name=$PACKAGE_NAME" >> $GITHUB_OUTPUT
        echo "package_main=$PACKAGE_MAIN" >> $GITHUB_OUTPUT
        echo "package_types=$PACKAGE_TYPES" >> $GITHUB_OUTPUT
        echo "package_description=$PACKAGE_DESCRIPTION" >> $GITHUB_OUTPUT
        echo "package_repository=$PACKAGE_REPOSITORY" >> $GITHUB_OUTPUT
        echo "package_author=$PACKAGE_AUTHOR" >> $GITHUB_OUTPUT
        echo "package_license=$PACKAGE_LICENSE" >> $GITHUB_OUTPUT
