@{
    Umbrella                  = "`u{2602}"   # ☂️ Umbrella
    RecyclingSymbol           = "`u{267B}"   # ♻️ Black Universal Recycling Symbol
    Gear                      = "`u{2699}"   # ⚙️ Gear
    MedicalSymbol             = "`u{2695}"   # ⚕️ Staff Of Aesculapius
    Anchor                    = "`u{2693}"   # ⚓ Anchor
    Warning                   = "`u{26A0}"   # ⚠️ Warning Sign
    WarningSign               = "`u{26A0}"   # ⚠️ Warning Sign
    NoEntry                   = "`u{26D4}"   # ⛔ No Entry
    Biohazard                 = "`u{2623}"   # ☣️ Biohazard
    Radioactive               = "`u{2622}"   # ☢️ Radioactive
    Heart                     = "`u{2764}"   # ❤️ Red Heart
    CheckMark                 = "`u{2705}"   # ✅ White Heavy Check Mark
    PaperPlane                = "`u{2708}"   # ✈️ Airplane
    Scissors                  = "`u{2702}"   # ✂️ Black Scissors
    Pencil                    = "`u{270F}"   # ✏️ Pencil
    Error                     = "`u{274C}"   # ❌ Cross Mark
    Star                      = "`u{2B50}"   # ⭐ Star
    Hourglass                 = "`u{231B}"   # ⌛ Hourglass
    Clock                     = "`u{23F0}"   # ⏰ Alarm Clock
    Stopwatch                 = "`u{23F1}"   # ⏱️ Stopwatch
    HourglassWithFlowingSand  = "`u{23F3}"   # ⏳ Hourglass With Flowing Sand
    Info                      = "`u{2139}"   # ℹ️ Information Source
    Books                     = "`u{1F4DA}"  # 📚 Books
    Globe                     = "`u{1F30D}"  # 🌍 Earth Globe Europe-Africa
    GlobeWithMeridians        = "`u{1F310}"  # 🌐 Globe With Meridians
    Flag                      = "`u{1F3C1}"  # 🏁 Chequered Flag
    Trophy                    = "`u{1F3C6}"  # 🏆 Trophy
    MusicNote                 = "`u{1F3B5}"  # 🎵 Musical Note
    PaintBrush                = "`u{1F3A8}"  # 🎨 Artist Palette
    Hospital                  = "`u{1F3E5}"  # 🏥 Hospital
    Rocket                    = "`u{1F680}"  # 🚀 Rocket
    RocketWithTrail           = "`u{1F680}"  # 🚀 Rocket
    ConstructionCone          = "`u{1F6A7}"  # 🚧 Construction
    Shield                    = "`u{1F6E1}"  # 🛡️ Shield
    Prohibited                = "`u{1F6AB}"  # 🚫 No Entry Sign
    Celebration               = "`u{1F389}"  # 🎉 Party Popper
    Gift                      = "`u{1F381}"  # 🎁 Wrapped Present
    Calendar                  = "`u{1F4C5}"  # 📅 Calendar
    Clipboard                 = "`u{1F4CB}"  # 📋 Clipboard
    Camera                    = "`u{1F4F7}"  # 📷 Camera
    MobilePhone               = "`u{1F4F1}"  # 📱 Mobile Phone
    Satellite                 = "`u{1F4E1}"  # 📡 Satellite Antenna
    SatelliteDish             = "`u{1F4E1}"  # 📡 Satellite Antenna
    FloppyDisk                = "`u{1F4BE}"  # 💾 Floppy Disk
    MagnifyingGlass           = "`u{1F50D}"  # 🔍 Left-Pointing Magnifying Glass
    Lock                      = "`u{1F512}"  # 🔒 Lock
    Keyhole                   = "`u{1F511}"  # 🔑 Key
    Key                       = "`u{1F511}"  # 🔑 Key
    Chain                     = "`u{1F517}"  # 🔗 Link Symbol
    Lightning                 = "`u{26A1}"   # ⚡ High Voltage
    Wrench                    = "`u{1F527}"  # 🔧 Wrench
    Microscope                = "`u{1F52C}"  # 🔬 Microscope
    Telescope                 = "`u{1F52D}"  # 🔭 Telescope
    GreenHeart                = "`u{1F49A}"  # 💚 Green Heart
    Syringe                   = "`u{1F489}"  # 💉 Syringe
    Pill                      = "`u{1F48A}"  # 💊 Pill
    Bandage                   = "`u{1FA79}"  # 🩹 Adhesive Bandage
    Stethoscope               = "`u{1FA7A}"  # 🩺 Stethoscope
    DNA                       = "`u{1F9EC}"  # 🧬 DNA Double Helix
    Compass                   = "`u{1F9ED}"  # 🧭 Compass
    Magnet                    = "`u{1F9F2}"  # 🧲 Magnet
    FireExtinguisher          = "`u{1F9EF}"  # 🧯 Fire Extinguisher
    PuzzlePiece               = "`u{1F9E9}"  # 🧩 Puzzle Piece
    TestTube                  = "`u{1F9EA}"  # 🧪 Test Tube
    Flask                     = "`u{1F9EB}"  # 🧫 Petri Dish
    Robot                     = "`u{1F916}"  # 🤖 Robot Face
    Map                       = "`u{1F5FA}"  # 🗺️ World Map
    Fire                      = "`u{1F525}"  # 🔥 Fire
    LightBulb                 = "`u{1F4A1}"  # 💡 Light Bulb
}
