/**
 * Domain Types Exports
 */

export type {
  LegacyLanguage,
  LegacyLanguageName,
  LegacyCountry,
  LegacyCountryName,
  LegacyProject,
  LegacyProjectName,
  LegacyMuseum,
  LegacyMuseumName,
  LegacyInstitution,
  LegacyInstitutionName,
  LegacyObject,
  ObjectGroup,
  LegacyMonument,
  MonumentGroup,
  LegacyMonumentDetail,
  MonumentDetailGroup,
  LegacyObjectPicture,
  LegacyMonumentPicture,
  LegacyMonumentDetailPicture,
  LegacyMuseumPicture,
  LegacyInstitutionPicture,
  LegacyDynasty,
  LegacyDynastyText,
  LegacyObjectDynasty,
  LegacyMonumentDynasty,
  LegacyAuthor,
  LegacyAuthorCv,
  LegacyShAuthorCv,
  LegacyAllAuthorMapping,
  LegacyAuthorObject,
  LegacyAuthorMonument,
  LegacyShAuthorObject,
  LegacyShAuthorMonument,
  LegacyAuthorDynasty,
  LegacyHcr,
  LegacyHcrEvent,
  LegacyObjectVideo,
  ShLegacyObjectVideoAudio,
  ShLegacyObjectDocument,
  ThgLegacyExhibitionMedia,
  ThgLegacyThemeMedia,
} from './legacy.js';

// Sharing History (SH) Legacy Types
export type {
  ShLegacyProject,
  ShLegacyProjectName,
  ShLegacyPartner,
  ShLegacyPartnerName,
  PartnerShPartnerMapping,
  ShLegacyObject,
  ShLegacyObjectText,
  ShObjectGroup,
  ShLegacyMonument,
  ShLegacyMonumentText,
  ShMonumentGroup,
  ShLegacyMonumentDetail,
  ShLegacyMonumentDetailText,
  ShMonumentDetailGroup,
  ShLegacyObjectImage,
  ShLegacyObjectImageText,
  ShLegacyMonumentImage,
  ShLegacyMonumentImageText,
  ShLegacyMonumentDetailPicture,
  ShLegacyMonumentDetailPictureText,
  ShLegacyPartnerPicture,
  ShLegacyHcr,
  ShLegacyHcrEvent,
  ShLegacyHcrImage,
  ShLegacyHcrImageText,
  ShLegacyBibliographyHcrCountry,
  ShLegacyBibliography,
  ShLegacyBibliographyLang,
} from './sh-legacy.js';
