title: Inventory-App
description: The Inventory Management API (inventory-app) is a RESTful API designed to manage the content of the Museum With No Frontiers' inventory database.
#show_downloads: true
#google_analytics:
#theme: jekyll-theme-leap-day

lsi: false
safe: true
source: gh-pages
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge