

# Deploy Laravel App
#

# NOTE: This workflow uses the GitHub environment "MWNF-SVR" for deployment.
# Set the following environment variables and secrets in the MWNF-SVR environment:
#   PHP_PATH, COMPOSER_PATH, NODE_PATH, MARIADB_PATH
# Do NOT hardcode sensitive or server-specific paths in this file for production.

name: Deploy on self-hosted MWNF-SVR environment

permissions:
  contents: read

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, windows]
    environment:
      name: MWNF-SVR
    env:
      PHP_PATH: ${{ vars.PHP_PATH }}
      COMPOSER_PATH: ${{ vars.COMPOSER_PATH }}
      NODE_PATH: ${{ vars.NODE_PATH }}
      NPM_PATH: ${{ vars.NPM_PATH }}
      MARIADB_PATH: ${{ vars.MARIADB_PATH }}
      ENV_PATH: ${{ vars.ENV_PATH }}
      MARIADB_DATABASE: ${{ secrets.MARIADB_DATABASE }}
      MARIADB_SECRET: ${{ secrets.MARIADB_SECRET }}
      MARIADB_USER: ${{ secrets.MARIADB_USER }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check required environment variables
        run: |
          Write-Host "Environment variables are configured in GitHub environment MWNF-SVR"
          Write-Host "PHP_PATH: $env:PHP_PATH"
          Write-Host "COMPOSER_PATH: $env:COMPOSER_PATH"
          Write-Host "NODE_PATH: $env:NODE_PATH"
          Write-Host "NPM_PATH: $env:NPM_PATH"
          Write-Host "MARIADB_PATH: $env:MARIADB_PATH"
          Write-Host "ENV_PATH: $env:ENV_PATH"
          Write-Host "MARIADB_DATABASE: $env:MARIADB_DATABASE"
          Write-Host "MARIADB_USER: $env:MARIADB_USER"
          Write-Host "MARIADB_SECRET: [REDACTED]"
        shell: powershell

      - name: Check PHP version
        run: |
          & "$env:PHP_PATH" -v
          if ((& "$env:PHP_PATH" -r "echo version_compare(PHP_VERSION, '8.2', '>=');") -ne 1) { exit 1 }
        shell: powershell

      - name: Check Composer
        run: |
          & "$env:COMPOSER_PATH" --version
        shell: powershell

      - name: Check Node.js
        run: |
          & "$env:NODE_PATH" --version
        shell: powershell

      - name: Check NPM
        run: |
          & "$env:NPM_PATH" --version
        shell: powershell

      - name: Check MariaDB
        run: |
          & "$env:MARIADB_PATH" --version
        shell: powershell

      - name: Ensure .env file exists
        run: |
          if (-not (Test-Path "$env:ENV_PATH")) {
            Write-Host ".env file not found, copying from .env.example..."
            Copy-Item ".env.example" "$env:ENV_PATH"
          }
          if (-not (Test-Path "$env:ENV_PATH")) {
            Write-Error ".env file is missing and could not be created. Deployment cannot continue."
            exit 1
          }
        shell: powershell

      - name: Install PHP dependencies
        run: |
          & "$env:COMPOSER_PATH" install --no-interaction --prefer-dist --optimize-autoloader
        shell: powershell

      - name: Install Node.js dependencies
        run: |
          & "$env:NPM_PATH" install --no-audit --no-fund
        shell: powershell

      - name: Build frontend assets
        run: |
          & "$env:NPM_PATH" run build
        shell: powershell

      - name: Run database migrations
        run: |
          & "$env:PHP_PATH" artisan migrate --force
        shell: powershell

      - name: Run Laravel tests
        run: |
          & "$env:PHP_PATH" artisan test
        shell: powershell

      - name: Laravel cache:clear
        run: |
          & "$env:PHP_PATH" artisan cache:clear
        shell: powershell

      - name: Laravel config:clear
        run: |
          & "$env:PHP_PATH" artisan config:clear
        shell: powershell

      - name: Laravel config:cache
        run: |
          & "$env:PHP_PATH" artisan config:cache
        shell: powershell

      - name: Laravel route:clear
        run: |
          & "$env:PHP_PATH" artisan route:clear
        shell: powershell

      - name: Laravel route:cache
        run: |
          & "$env:PHP_PATH" artisan route:cache
        shell: powershell

      - name: Laravel view:clear
        run: |
          & "$env:PHP_PATH" artisan view:clear
        shell: powershell
