name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: windows-latest

    steps:
    - uses: shivammathur/setup-php@v2
      with:
        # php-version: '8.2'  # If not specified, setup-php will use the version defined in composer.lock
        extensions: fileinfo, zip
        coverage: xdebug
        tools: pint, phpunit, pest
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: |
        # composer update
        composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Create .env file
      run: |
        if(-not(Test-Path ".env")) {
          Copy-Item .env.testing .env
        }
    - name: Generate key
      run: php artisan key:generate
    - name: Execute linter via Pint (the Laravel's official Linter)
      run: |
        ./vendor/bin/pint --test
    - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/testing.sqlite
      run: |
        php artisan migrate --env=testing --force
        php artisan test --coverage
        
